### ISSUE TITLE
Crashed when save path contains Chinese/Japanese/Korea charactors

### ISSUE THREAD

**Issue by fasthold** [BKSalman/ytdlp-gui#12]
OS: Window 11

When select save path which contains Chinese/Japanese/Korea charactors, the GUI crashed.

**Comment by BKSalman** [comment]
can you give me a directory name that I can use to reproduce this issue?

**Comment by BKSalman** [comment]
closing for no reply

**Comment by BKSalman** [comment]
@fasthold

**Comment by BKSalman** [comment]
I will merge the changes to main, if they don't fix the issue, feel free to reopen the issue
