### ISSUE TITLE
Download finished but video not found (Windows 10)

### ISSUE THREAD

**Issue by SimonGhoul** [BKSalman/ytdlp-gui#13]
Is there any way to figure out why this is not working? The application doesn't give me much to work with when it comes to figure out why it failed. There's no logs or anything.

When I clicked the download button, it says initializing. After a few seconds, it says finished (even if the video is 10hrs long, it does it in 10 seconds). I had tried changing the directory already and using different settings.
![image](https://user-images.githubusercontent.com/41213690/219970062-a442ff51-78d8-4331-821c-976911404ab9.png)
It's all on the same folder

**Comment by BKSalman** [comment]
Hey, thanks for taking the time and reporting this, this is probably related to a bug that recently got introduced due to YouTube changing their url for channels from ``/channel/foo`` to ``/@foo``, and that broke yt-dlp.

However it was since fixed, but I just didn't get the chance to update the version I have in the release page, I will make sure to update it whenever I can tho!!

Also, I realize logging needs to be addressed, so I will be fixing that as well!

**Comment by SimonGhoul** [comment]
Hey great to know! I appreciate the response and good work

**Comment by SimonGhoul** [comment]
Wait, I think that issues might be unrelated because this happens to me when I download videos, not youtube channels.

**Comment by BKSalman** [comment]
> I think that issue might be unrelated because this happens to me when I download videos, not youtube channels.

It could be related, since I have encountered this issue personally, could you try to check it after replacing the yt-dlp.exe with the latest release from its GitHub repo please?

**Comment by BKSalman** [comment]
> Hey great to know! I appreciate the response and good work

Thanks! :)

**Comment by SimonGhoul** [comment]
> > I think that issue might be unrelated because this happens to me when I download videos, not youtube channels.
> 
> It could be related, since I have encountered this issue personally, could you try to check it after replacing the yt-dlp.exe with the latest release from its GitHub repo please?

Hey it's working! Sorry I am doing a lot of things at once right now, kind of overwhelmed and distracted

**Comment by BKSalman** [comment]
> > > I think that issue might be unrelated because this happens to me when I download videos, not youtube channels.
> 
> > 
> 
> > It could be related, since I have encountered this issue personally, could you try to check it after replacing the yt-dlp.exe with the latest release from its GitHub repo please?
> 
> 
> 
> Hey it's working! Sorry I am doing a lot of things at once right now, kind of overwhelmed and distracted

Hahah, it's alright, glad that it worked! Will get on it whenever I can

**Comment by BKSalman** [comment]
released [new version](https://github.com/BKSalman/ytdlp-gui/releases/tag/v0.2.5) that fixes this issue
