### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by eclairevoyant** [BKSalman/ytdlp-gui#15]
* Having multiple radio buttons on one line is very confusing as you can't necessarily tell which button corresponds to which option. Usually it should be one radio button per line (see point 6 here: https://www.nngroup.com/articles/checkboxes-vs-radio-buttons/)
* The "Browse..." button should be on the right side of the field to be consistent with most applications
* "Download" button should be on its own line/area at the bottom right (I'm not sure how this is best done in iced)

**Comment by BKSalman** [comment]
Hey,
thanks for the suggestions!

I will try them out once I have some free time, and see if I like em

I kinda agree with you anyways, but this project needs a bit of updating and cleaning up, so will do that when I have some free time

**Comment by eclairevoyant** [comment]
No worries, thanks for considering it either way.

> I didn't get notified about this issue

The Github settings are a bit convoluted, you have to be "watching" this repo and then there is a separate notification setting controlling whether you get emails and/or GH notifs for watched repos. I just ran into the smae issue for one of my repos 😅

**Comment by BKSalman** [comment]
> The Github settings are a bit convoluted, you have to be "watching" this repo and then there is a separate notification setting controlling whether you get emails and/or GH notifs for watched repos. I just ran into the same issue for one of my repos sweat_smile

ah, got it, thanks, I just enabled it in my settings now :package: 

regarding the issue, will start working on updating the project to latest iced version, and refactor small things, then will try out the suggested UX changes, will do a PR so you can track the progress whenever I start working on all of these

**Comment by BKSalman** [comment]
I think this was addressed in #16
