### ISSUE TITLE
Will you create a winget pkg ?

### ISSUE THREAD

**Issue by linux-player9** [BKSalman/ytdlp-gui#17]
Your program is awesome ! I was wondering if you will create a winget package so that ytdlp-gui could be installed via a command like : 

winget install BKSalman.ytdlp-gui

Or maybe a scoop package

**Comment by BKSalman** [comment]
> Your program is awesome ! 

ayyy thanks, really appreciate it, glad that you find it useful :)

> I was wondering if you will create a winget package so that ytdlp-gui could be installed via a command like :
>
>winget install BKSalman.ytdlp-gui
>
>Or maybe a scoop package

honestly I have no idea how scoop or winget work, can the package be install via a file like the `.deb`/`.rpm` package?

if so, I would really appreciate it if someone would contribute with a `winget`/`scoop` package :)

if no one want to, I might give a shot (later :tm:)

**Comment by BKSalman** [comment]
also, I don't have a way of testing it since I don't use Windows :p

**Comment by BKSalman** [comment]
since there is nothing that can be done here, I will close the issue, feel free to open a pull request if you want to add the `winget`/`scoop` package (I don't even know if you can PR them)
