### ISSUE TITLE
Sponsorblock and chapters support?

### ISSUE THREAD

**Issue by slrgt** [BKSalman/ytdlp-gui#27]
Hi, love the project! Are there any plans to support the SponsorBlock and Chapters flags that yt-dlp has?

**Comment by BKSalman** [comment]
Hello! Thanks for the kind words, I haven't looked into it honestly, but I'm open to suggestions and contributions if anyone is interested, or I will just work on it myself (will probably take a long time)

Anyways, can you give suggestions on how the feature would look like GUI wise? Maybe just a checkbox?

**Comment by slrgt** [comment]
Yeah i think a checkbox would be best and the option to set it to be enabled by default

**Comment by BKSalman** [comment]
Will look into it when I'm free inshallah

**Comment by BKSalman** [comment]
085c4ccc44b5eb223d679a893751f5e625f8f6a7 handles that now, just need to release it after #38 is merged

**Comment by BKSalman** [comment]
I implemented it as a pick list in 84693e0 instead of a checkbox in 085c4cc to allow either marking or removing sponsors.
