### ISSUE TITLE
Proposal: Resumable downloads for long queues

### ISSUE THREAD

**Issue by sgtrusty** [BKSalman/ytdlp-gui#28]
## Rationale
Resumable downloads for long queues.
- Reference: https://github.com/MrS0m30n3/youtube-dl-gui

In that lib, you can provide a link and it gets added to the download queue. Starting this issue because this is the only gui source project I found with compatibility with my setup (arch linux). Tooling is also nice, I am a rust newbie but I have contributed to open source python / javascript libs in the past so I can definitely put some initiative here. I also think that the nix streamlining will be interesting to look at for me.

## Solution
1. Links being downloaded are added to a queue and put in an output folder when complete.
2. In case program is exited or system becomes down, queue will be saved and transfer progresses.
    - Transfer progresses are not so important here functionally, since yt-dlp already takes care of that. We just need to know which urls to resume downloading.
3. Et voilà, this program grows a little bit in scope but adapts to my need.

## Reference images
- internet download manager: site querying
![internet download manager](https://github.com/BKSalman/ytdlp-gui/assets/48886164/78b05fd2-376a-495a-a3ad-699bd8afe7e3)
- jdownloader: download playlist
![jdownloader](https://github.com/BKSalman/ytdlp-gui/assets/48886164/dd536650-7e63-406f-953c-4a19a05a894d)

**Comment by BKSalman** [comment]
Good idea, just needs a little bit of ui change, maybe adding an arrow button next to the download button that toggles the download queue list view, also not too complicated since resuming downloads is handled by yt-dlp.

A PR is welcome if you want to contribute this feature, otherwise I can get on it when I'm free :)

**Comment by BKSalman** [comment]
Also not sure if iced (or iced-aw) provides a table widget

**Comment by BKSalman** [comment]
Np, thank you for sharing other nice projects :), could be a decent source of inspiration

**Comment by BKSalman** [comment]
started a new [branch](https://github.com/BKSalman/ytdlp-gui/tree/download-queue) for this feature, hopefully I can have enough free time to finish it quickly

**Comment by BKSalman** [comment]
I think this feature won't be implemented in the near future since the application design is very simple, and I'm planning to keep it that way.

I might change my mind later tho, but no promises.
