### ISSUE TITLE
save and restore main window position

### ISSUE THREAD

**Issue by megabugman** [BKSalman/ytdlp-gui#31]
hey, nice app, I like the clean UI. 👍

please add:
Save the window position in ini file or similar in the app folder to keep it portable when exiting and restore after restarting the application

**Comment by BKSalman** [comment]
what OS are you running?

if it's linux, what desktop are you using, and is it running on wayland or x11?

**Comment by megabugman** [comment]
Windows 10

**Comment by BKSalman** [comment]
this is not necessarily desirable by everyone, so I might add a setting that's only configurable from the configuration file.

if I decide to add a settings menu later I could add it there as well

**Comment by BKSalman** [comment]
added here [917f2c2](https://github.com/BKSalman/ytdlp-gui/commit/917f2c2964da88784fe0a16e66a55983a458329a)
