### ISSUE TITLE
add context menu to paste URL

### ISSUE THREAD

**Issue by megabugman** [BKSalman/ytdlp-gui#32]
I. please add, something similar:
![image](https://github.com/BKSalman/ytdlp-gui/assets/17204819/f50f34a8-3402-417e-a1ac-7b761feba6bd)

I want to add URLs using the mouse not only hotkey ctrl+v.

II. also the main window title "Youtube Downloader" is misleading as many websites are supported by  yt-dlp.
III: also please consider adding a fancy program icon ;)

cheers

OS: Win10

**Comment by BKSalman** [comment]
> I. please add, something similar:
> 
> ![image](https://github.com/BKSalman/ytdlp-gui/assets/17204819/f50f34a8-3402-417e-a1ac-7b761feba6bd)
> 
> 
> 
> I want to add URLs using the mouse not only hotkey ctrl+v.
> 

Sure, when this is resolved: https://github.com/rust-windowing/winit/issues/403

> 
> II. also the main window title "Youtube Downloader" is misleading as many websites are supported by  yt-dlp.

I personally think it's fine, but what do you suggest instead?

> III: also please consider adding a fancy program icon ;)

This is platform specific, and I don't know how packaging windows apps work, and how you attach icons to it (I mean the whole windows package is just a portable zip file, which shows I don't know/want to deal with it)

**Comment by megabugman** [comment]
I have no experience with Rust, but I couldn't imagine that adding a context menu would be so difficult. 😁
As for the name, since this application is a user interface for ytdlp, you might want to give it a name that reflects this fact, or keep the title but change it to You**T**ube Downloader.  
Regarding the icon I will then add myself when the muse kisses me.

**Comment by BKSalman** [comment]
> I have no experience with Rust, but I couldn't imagine that adding a context menu would be so difficult. 😁

It's not a rust specific issue, it's mostly because so many OSs have so many ways to display a context menu, so winit and iced want to be cross-platform and that makes it harder to implement, and take more time

But when it's there it shouldn't be too hard to use

> As for the name, since this application is a user interface for ytdlp, you might want to give it a name that reflects this fact, or keep the title but change it to You**T**ube Downloader.  

Maybe a unique name could be the best option here, but that could make the project less findable

> Regarding the icon I will then change it myself when the muse kisses me.

Good luck :)

**Comment by BKSalman** [comment]
closed since the context menu issue can't be resolved by me
