### ISSUE TITLE
Current release on AUR is out of date

### ISSUE THREAD

**Issue by rcky844** [BKSalman/ytdlp-gui#33]
I've already flagged it on the site itself, but the deps it uses are out of date. Please create a new GitHub release, thanks!

**Comment by BKSalman** [comment]
> I've already flagged it on the site itself, but the deps it uses are out of date. Please create a new GitHub release, thanks!

Yeah thank you for the reminder, I was in the middle of updating it and got busy, so I will probably do it tomorrow when I have time

**Comment by BKSalman** [comment]
@rcky844 can you check the latest update to the package please? (I don't use arch :p)

**Comment by csutcliff** [comment]
you also need to update the sha256sum of the latest tar.gz when you update the pkgbuild or it won't verify

**Comment by BKSalman** [comment]
Damn, forgot to do that, will get on it soon inshallah

**Comment by BKSalman** [comment]
IDK why my xtask didn't just do it by itself, anyways, can you check it now?

**Comment by csutcliff** [comment]
all good now

**Comment by BKSalman** [comment]
cool :tada:, thank you for testing!
