### ISSUE TITLE
Can't see text, weird rendering

### ISSUE THREAD

**Issue by dukcc** [BKSalman/ytdlp-gui#34]
Under some dropdowns I can see the text but it's some weird hard to read gradient, and most of the other program there is no text.

Running arch linux & gnome

![image](https://github.com/user-attachments/assets/572be08e-bdf7-4d59-9a9c-1a83f4199ce4)
![image](https://github.com/user-attachments/assets/dfbe2c83-5856-495f-97a8-3f6ba903e950)

**Comment by BKSalman** [comment]
That's a pretty weird issue, what version are you on?

**Comment by dukcc** [comment]
> That's a pretty weird issue, what version are you on?

latest commit I think, I just downloaded it from the AUR

**Comment by BKSalman** [comment]
can you test previous versions?

**Comment by BKSalman** [comment]
closing for no reply
