### ISSUE TITLE
Start with Download Link Text field focused

### ISSUE THREAD

**Issue by megabugman** [BKSalman/ytdlp-gui#35]
Hey,

I would like to automate the user interface, but it is not easy as no standard Windows controls are used.
Since the tab key is not supported, I would appreciate if you could add an option or have the edit box focused as default when starting the app, so that I only have to press the key combination Ctrl + V to download faster:

![image](https://github.com/user-attachments/assets/528ec92c-3245-4a5a-9c86-ee4c0eed66ca)

It would also be helpful if the controls supported the tab key. Pressing the tab key would focus the next control element to enable automation.

**Comment by BKSalman** [comment]
if you want that to happen so you can download multiple videos at the same time you can just paste all of them separated by space into the text box

**Comment by megabugman** [comment]
Not exactly. I want to automate the Download. ATM, I need to do all the steps manually.
![enhance](https://github.com/user-attachments/assets/c6c96954-a274-40aa-ab9a-302ccd767b6b)

I cam automate the program start, but as tab is not supported (and/or the text box is not focused) I cannot paste the link.
I need to manually click on the text box. Then I can paste the Link. Then I need to move the mouse over the download button and click. I want to automate pressing a few times tab instead until the download button is active, then automate a return key.

**Comment by BKSalman** [comment]
Why not just make a script that uses yt-dlp directly?

**Comment by megabugman** [comment]
Good point. 👍

**Comment by BKSalman** [comment]
> I found some working scripts, but I guess I like your UI with the progressbar. 

Doesn't yt-dlp already show a progress bar? Or you just like the my application's UI?

> Feel free to close this, if this is another iced issue or you don't want to add such feature.

If it's possible I don't mind doing it, I will check that out

**Comment by megabugman** [comment]
yt-dlp is a CLI, runs in command prompt. I like your UI, for it's simplicity. Unfortunately, the frame work you're using has no windows standard controls and hence it's difficult to automate properly.

If possible consider adding hotkeys to the buttons like e.g. ctrl+d for download button, also for toggling the audio / video setting. This might be helpful for others.

Maybe you want to have only one Window, instead of two, ATM one has to click quite often after each video download:
![image](https://github.com/user-attachments/assets/b3d9167d-6b50-4cee-b2df-7b3398455979)

As a work-around for the missing context menu, I have automated it, so I can keep my hand on the mouse:

`#Requires AutoHotkey v2.0
#SingleInstance Off

Run "D:\ytdlp-gui.exe",,,&PID ?? 0

#HotIf WinActive("ahk_exe ytdlp-gui.exe")
	RButton::Send('^v') ; Send Ctrl+V
#HotIf

ProcessWaitClose(PID)
ExitApp
`

**Comment by BKSalman** [comment]
> If possible consider adding accelerator keys to the buttons like e.g. ctrl+d for download button, also for toggling the audio / video setting and Esc to close Windows/Main Application. This might be helpful for others.

That's not a bad idea, I could add keyboard shortcuts

> Maybe you want to have only one Window, instead of two, ATM one has to click quite too often after each video download:
> 
> ![image](https://github.com/user-attachments/assets/b3d9167d-6b50-4cee-b2df-7b3398455979)

Will look into changing the ui to something better, but this is missing a download cancellation button

Thanks for the suggestions

**Comment by megabugman** [comment]
Correct. Cancel is missing, You could add a small X inside or next to to the progress-bar.
![image](https://github.com/user-attachments/assets/e6fa7236-40b5-46aa-8533-0ecd8c6b97c4)

**Comment by BKSalman** [comment]
The application now starts with the text input being focused

Also there was a cli flag that was added to start the application with the provided url, that will make even better to automate
