### ISSUE TITLE
url in command line

### ISSUE THREAD

**Issue by coding-moding** [BKSalman/ytdlp-gui#37]
I would like to add --url command line argument to be filled in download link text box. It's convinient to use to automatially open youtube links from browser.  I would do PR if I know how to set download_link from fn main().

**Comment by BKSalman** [comment]
No problem, go ahead.

If you have any questions feel free to ask here :)

**Comment by BKSalman** [comment]
Here is how you could add a cli flag (even tho I might change it to use [clap](https://docs.rs/clap/latest/clap/) later, to make it more scalable):
https://github.com/BKSalman/ytdlp-gui/blob/main/src/main.rs#L12-L29

**Comment by coding-moding** [comment]
Thanks for detailed explanation. Added the corresponding PR: 
https://github.com/BKSalman/ytdlp-gui/pull/38

**Comment by BKSalman** [comment]
> Thanks for detailed explanation. Added the corresponding PR: 
> 
> https://github.com/BKSalman/ytdlp-gui/pull/38

Thank you for contributing, will check it when I'm free 👍

**Comment by BKSalman** [comment]
merged #38 :) :+1:
