### ISSUE TITLE
Multi URL input

### ISSUE THREAD

**Issue by rew1nter** [BKSalman/ytdlp-gui#39]
A multi URL input system where all the settings are same for every video would be great

**Comment by BKSalman** [comment]
Implementing this into the UI could add more issues than it would solve.

You can instead just paste all the links separated by space, and click download, it should download them all

If that has issues you can report back

**Comment by rew1nter** [comment]
Nope that did not work. It just downloaded one video and stopped

**Comment by BKSalman** [comment]
@rew1nter I added that functionality into 86b27ce try it out, and see if there is any bugs with it

**Comment by rew1nter** [comment]
I can get this new version from yay right?

**Comment by BKSalman** [comment]
Not yet, I have to release it, you need to build it from source if you want to test it

**Comment by BKSalman** [comment]
I just released a new version on the AUR, you can check it out
