### ISSUE TITLE
Idea/Feature request: Time date downloads

### ISSUE THREAD

**Issue by Vramuser** [BKSalman/ytdlp-gui#43]
Have an option to download videos from specific time periods.
Why? I would like this because, when archiving a YouTube channel, I want to download videos from certain dates.

**Comment by BKSalman** [comment]
You mean the application would get all videos of a channel from a specific range of dates?

**Comment by Vramuser** [comment]
Yeah, sorry if I was unclear. I was doing something at the time.

**Comment by BKSalman** [comment]
No worries I was just trying to understand it clearly.

Unfortunately that's out of the scope of the application.

Tho you can automate the application by using the cli flags, like `--url` and provide multiple urls separated by a space

That will allow you to make a script that does all the fetching of urls, then passes them into the `--url` cli flag

**Comment by Vramuser** [comment]
Oh, ok then have a great day or night!

**Comment by BKSalman** [comment]
you too mate :)

if you need anything else feel free to open another issue
