### ISSUE TITLE
v. for Windows opens and immediately closes GUI

### ISSUE THREAD

**Issue by Yuriy-II** [BKSalman/ytdlp-gui#46]
I've tried versions: 2.0.0, 1.1.1, 1.1.0. All has the same issues:
1) Files in archive are dated 01.01.1980
2) When launching ytdlp-gui.exe (my account has administrator privileges), windows opens and immediately closes.

Version 0.3.0 works fine. Has proper dates: 27/07/2023

**Comment by BKSalman** [comment]
> I've tried versions: 2.0.0, 1.1.1, 1.1.0. All has the same issues:
> 
> 1) Files in archive are dated 01.01.1980

This shouldn't be a big issue, and the application should work nonetheless.

> 2) When launching ytdlp-gui.exe (my account has administrator privileges), windows opens and immediately closes.
> 

Can you post the logs of the application?

**Comment by Yuriy-II** [comment]
> Can you post the logs of the application?

Where can I find them?

**Comment by BKSalman** [comment]
> > Can you post the logs of the application?
> 
> 
> 
> Where can I find them?

Should be somewhere around this path `C:\Users\Alice\AppData\Local`

**Comment by Yuriy-II** [comment]
**warnings.2024-12-23** : file empty
**debug.2024-12-23-19-43** :
2024-12-23T19:43:08.941807Z  INFO ytdlp_gui: config loaded: Config {
    bin_dir: None,
    download_folder: Some(
        "D:\\Downloads2",
    ),
    save_window_position: false,
    window_position: None,
    url: None,
    options: Options {
        video_resolution: FullHD,
        video_format: Mp4,
        audio_quality: Good,
        audio_format: Mp3,
    },
}

**Comment by Yuriy-II** [comment]
Above text comes from debug.2024-12-23-19-43 after I launched v2.0.0
It has `"D:\\Downloads2"` as text. With double backslash.

How I can reset settings to default?

**Comment by BKSalman** [comment]
hmmm, not very useful logs.

can you open the application with something like
```powershell
$env:YTG_LOG = 'trace'; ./ytdlp-gui.exe > logs.txt
```

this should spit out a LOT of logs to a file `logs.txt`

**Comment by Yuriy-II** [comment]
d:\Downloads2\ytdlp-gui-windows-64>ytdlp-gui.exe $env:YTG_LOG = 'trace'; ./ytdlp-gui.exe > logs.txt
Contents of **logs.txt**:
`Invalid option/argument`

d:\Downloads2\ytdlp-gui-windows-64>yt-dlp.exe $env:YTG_LOG = 'trace'; ./ytdlp-gui.exe > logs.txt
Contents of **logs.txt**:
_[generic] Extracting URL: $env:YTG_LOG
[generic] Extracting URL: =
[generic] Extracting URL: 'trace';
[generic] Extracting URL: ./ytdlp-gui.exe_

**Comment by BKSalman** [comment]
no you shouldn't add `./ytdlp-gui.exe` to the beginning, just `$env:YTG_LOG = 'trace'; ./ytdlp-gui.exe > logs.txt`

**Comment by Yuriy-II** [comment]
After some research:


At least on Windows 7 the following works in the default terminal

mycommand > log.txt 2> errorlog.txt

The > log.txt will catch the output to a file called "log.txt", and 2> errorlog.txt will catch the errors to a file called "errorlog.txt"

So I
d:\Downloads2\ytdlp-gui-windows-64>**ytdlp-gui.exe** > log.txt 2> errorlog.txt

Contents of **log.txt** :
```
[2m2024-12-23T20:01:35.375400Z[0m [32m INFO[0m [2mytdlp_gui[0m[2m:[0m config loaded: Config {
    bin_dir: None,
    download_folder: Some(
        "D:\\Downloads2",
    ),
    save_window_position: false,
    window_position: None,
    url: None,
    options: Options {
        video_resolution: FullHD,
        video_format: Mp4,
        audio_quality: Good,
        audio_format: Mp3,
    },
}

```
**errorlog.txt**  is empty.

**Comment by BKSalman** [comment]
> After some research:
> 
> At least on Windows 7 the following works in the default terminal
> 
> mycommand > log.txt 2> errorlog.txt
> 
> The > log.txt will catch the output to a file called "log.txt", and 2> errorlog.txt will catch the errors to a file called "errorlog.txt"
> 
> So I d:\Downloads2\ytdlp-gui-windows-64>**ytdlp-gui.exe** > log.txt 2> errorlog.txt
> 
> Contents of **log.txt** :
> 
> ```
> �[2m2024-12-23T20:01:35.375400Z�[0m �[32m INFO�[0m �[2mytdlp_gui�[0m�[2m:�[0m config loaded: Config {
>     bin_dir: None,
>     download_folder: Some(
>         "D:\\Downloads2",
>     ),
>     save_window_position: false,
>     window_position: None,
>     url: None,
>     options: Options {
>         video_resolution: FullHD,
>         video_format: Mp4,
>         audio_quality: Good,
>         audio_format: Mp3,
>     },
> }
> ```
> 
> **errorlog.txt** is empty.

makes sense, you just need to add the environment variable `$env:YTG_LOG = 'trace'; ./ytdlp-gui.exe > logs.txt`

**Comment by Yuriy-II** [comment]
Both 
d:\Downloads2\ytdlp-gui-windows-64>ytdlp-gui.exe > log.txt 2> errorlog.txt $env:YTG_LOG = 'trace'
d:\Downloads2\ytdlp-gui-windows-64>ytdlp-gui.exe $env:YTG_LOG = 'trace' > log.txt 2> errorlog.txt

return
log.txt : `Invalid option/argument`
errorlog.txt : empty

**Comment by BKSalman** [comment]
the full command should look something like this: (with no ytdlp-gui.exe at the beginning)
```powershell
$env:YTG_LOG = 'trace'; ./ytdlp-gui.exe > logs.txt 2> errorlog.txt
```

**Comment by Yuriy-II** [comment]
Launching in CMD from `d:\Downloads2\ytdlp-gui-windows-64>`
`$env:YTG_LOG = 'trace'; ./ytdlp-gui.exe > logs.txt 2> errorlog.txt`

errorlog.txt : The filename, directory name, or volume label syntax is incorrect.
logs.txt : empty

**Comment by BKSalman** [comment]
this won't work on CMD, only powershell (if the command is correct)

**Comment by Yuriy-II** [comment]
Same result for `$env:YTG_LOG = 'trace'; ytdlp-gui.exe > logs.txt 2> errorlog.txt` and `$env:YTG_LOG = 'trace' ytdlp-gui.exe > logs.txt 2> errorlog.txt`

**Comment by Yuriy-II** [comment]
Running in Windows PowerShell 7 (x64):
from _D:\Downloads2\ytdlp-gui-windows-64>_
`$env:YTG_LOG = 'trace'; ./ytdlp-gui.exe > logs.txt 2> errorlog.txt`
errorlog.txt : empty
logs.txt : empty

**Comment by BKSalman** [comment]
> Running in Windows PowerShell 7 (x64): from _D:\Downloads2\ytdlp-gui-windows-64>_ `$env:YTG_LOG = 'trace'; ./ytdlp-gui.exe > logs.txt 2> errorlog.txt` errorlog.txt : empty logs.txt : empty

did the application even run?

**Comment by Yuriy-II** [comment]
Doesn't look like it: no window appeared.

Running `.\ytdlp-gui.exe` from _D:\Downloads2\ytdlp-gui-windows-64>_ in Windows PowerShell 7 (x64) results in window opening and closing immediately.

**Comment by Yuriy-II** [comment]
Running `.\ytdlp-gui.exe > logs.txt 2> errorlog.txt` with same as above :
errorlog.txt : empty
logs.txt : empty

**Comment by BKSalman** [comment]
very strange.

I can't really test this unfortunately, since I don't use Windows.

**Comment by Yuriy-II** [comment]
Programs tries to run with same result.
output.txt : empty

**Comment by BKSalman** [comment]
try this in CMD:
```cmd
set YTG_LOG=trace && ytdlp-gui.exe > output.txt 2>&1
```

**Comment by Yuriy-II** [comment]
Running in CMD `d:\Downloads2\ytdlp-gui-windows-64>set YTG_LOG=trace && ytdlp-gui.exe > output.txt 2>&1`
Window opens and closes immediately.
output.txt :
`ignoring `trace `: invalid filter directive
[2m2024-12-23T20:35:13.636762Z[0m [31mERROR[0m [2mwgpu_hal::vulkan::instance[0m[2m:[0m enumerate_adapters: A return array was too small for the result    `

**Comment by BKSalman** [comment]
hmm, looks like a graphics issue, something to do with your hardware or drivers.

will investigate how this could be solved

**Comment by Yuriy-II** [comment]
If it helps: I'm on notebook which has integrated AMD graphics and nVidia graphics card.

**Comment by Yuriy-II** [comment]
I have updated drivers for integrated AMD chips (processor and integrated graphics) using **amd-software-adrenalin-edition-24.12.1-minimalsetup-241204_web.exe**
Now v 2.0.0 works fine!

Thank you.

**Comment by BKSalman** [comment]
Nice! Glad it works now
