### ISSUE TITLE
error invalid URL on position: 1 when copy video URL

### ISSUE THREAD

**Issue by megabugman** [BKSalman/ytdlp-gui#47]
cannot download video link: https://youtu.be/Q-mvFxRHjtg
![image](https://github.com/user-attachments/assets/0680031f-cb41-49fa-8942-86063b645b9d)

download fails with error:
![image](https://github.com/user-attachments/assets/b396fd42-a8a1-4461-855e-417a3110b7ce)

download works without issue using another gui:
![image](https://github.com/user-attachments/assets/9005b045-003a-4541-a221-c299ec202057)

**Comment by BKSalman** [comment]
fixed in 89d4417
