### ISSUE TITLE
Links in the input field from YouTube are not copied

### ISSUE THREAD

**Issue by IGraffusI** [BKSalman/ytdlp-gui#48]
I tried to move the link using Ctrl+C and Ctrl+V, but it doesn't want to paste

**Comment by BKSalman** [comment]
What system are you using? Windows or Linux?

**Comment by IGraffusI** [comment]
Windows 10

**Comment by BKSalman** [comment]
Which version of the application?

**Comment by IGraffusI** [comment]
2.0.0

**Comment by BKSalman** [comment]
try this in CMD:
```cmd
set YTG_LOG=trace && ytdlp-gui.exe > output.txt 2>&1
```

**Comment by IGraffusI** [comment]
Thank you very much!

**Comment by BKSalman** [comment]
I forgot to tell you to post the output file, that was the reason for the command I sent lol.

But since it works now, that might mean the application didn't have an issue in the first place.
